### ISSUE TITLE
64bit support

### ISSUE THREAD

**Issue by razims** [mikha-dev/mtmanapi#1]
Hi Mikhail,

do you know how to make it work with mtmanapi64.dll ? I set GOARCH=amd64 for compiling.  

1. Reverted your patches in MT4ManagerAPI.h
2. Run swig with `swig  -Wall  -go -cgo  -c++ -intgosize 64 mtmanapi.i`

It compiles, but produces weird stuff especially when I get strings.

**Comment by mikha-dev** [comment]
Hi Razim,

I also tried to compile and use 64 version of mt4 man api. but never got it working. The same issue with strings.

**Comment by razims** [comment]
Thank you for your promt reply Mikhail.

I spent couple of nights on this, never worked with 64bit. Strangely my C++/CLI wrapper does work with 64bit library.  

I assume it has something to do with windows.i swig include file. Since it is adjusted for 32Bit systems as mentioned in the header comment.  

I would accept 32bit version, but I have another problem there. Didn't manage to debug it. How you do that on your side ?
